### PR TITLE
fix: considers the original index of the excel or csv to preserve the original order

### LINKED ISSUE #231: ORDERING ISSUE: maintain the order of the rows from the spreadsheet
### Describe what should be investigated or refactored

When rows have parenthesis the ordering can become wonky, we need a way to find a better more predictable ordering system for grouping of controls. It seems to be in alphabetical order right now which causes pain when you are trying to look at similar controls

### PR DESCRIPTION
**Pull request by cmwylie19**
## Description

This fixes a pain-point from the way the ordering is currently happening in the UI. This PR considers the original index and sorts controls based on that index.

If we want to use this feature retro-actively then we can bring in this [PR](https://github.com/defenseunicorns/uds-compliance/pull/65)

## Related Issue

Fixes #231 

Relates to #

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: cli/server/spreadsheetRoutes.ts [hunk 1]
```diff
@@ -550,13 +551,18 @@ export async function createOutputStructure(
 		params.namingConvention
 	);
 
+	const controlOrder = controls
+		.sort((a: any, b: any) => (a._originalRowIndex || 0) - (b._originalRowIndex || 0))
+		.map((control: any) => control[controlIdFieldNameClean]);
```
Comment (mjnagel) [inline cli/server/spreadsheetRoutes.ts:556]: I'm unsure on this approach. I wonder if we can more generically sort post-import rather than having to store the order during the import?

But this may also depend on whether preserving order of the original spreadsheet is important.

Comment (mjnagel) [reply cli/server/spreadsheetRoutes.ts:556]: After discussion - I think going with the original spreadsheet order makes a lot of sense and ensures we keep this generic. It keeps the original user intent as well, and leaves room for us to do custom sorting in the UI later.

**Review by mjnagel — APPROVED** [review]
