### PR TITLE
fix: fixes around nist 800 rev 5 controls

### LINKED ISSUE #340: When justifications share same UUID only one shows up in the mappings view
### Environment

This is a unique problem that occurred in NIST 800 Rev 5 after migrating our Rev 4 controls.

```yaml
- uuid: 123-asdf-123
  justification: justification 1
- uuid: 123-asdf-123
  justification: justification 2
```

Only one of them will show up in the UI

Image

### Steps to reproduce

1. Create a mapping with 2 or more justifications with the same UUID and open it in the UI

### Expected result

See all of the results

### Actual Result

See one result

### Severity/Priority

High - it is for rev 5 work and makes life harder by forcing you to double check your yaml

### Additional Context

Add any other context or screenshots about the technical debt here.

### PR DESCRIPTION
**Pull request by cmwylie19**
## Description

Fixes around shared UUID that came up when we migrated from NIST 800 Rev 4 to NIST 800 Rev 5. This PR changes the way that the mappings are held in ephemeral memory to allow the Lula UI to display mappings that share UUID and `control_id`

Notable Changes:
- The ephemeral state (for mappings), mainly `map[string]interface{}` uses a new key, hash, which is the sha256sum of the mapping.
- The checksums must be created on the backend. There is webcrypto but it is not supported in all browsers
- There was a general agreement not to create any breaking changes, ie, the mappings can remain as it and when being read from the filesystem the hash will be generated.

## Related Issue

Fixes #340 

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: src/lib/components/controls/MappingCard.svelte [hunk 1]
```diff
@@ -23,8 +23,8 @@
 	}
 
 	function handleDelete() {
-		if (confirm('Are you sure you want to delete this mapping?')) {
-			onDelete?.(mapping.uuid);
+		if (confirm('Are you sure you want to delete this mapping?'+ mapping.uuid  + '')) {
+			onDelete?.(mapping.hash || '');
```
Comment (cmwylie19) [inline src/lib/components/controls/MappingCard.svelte]: this cannot be empty, use `!`

File: src/lib/components/controls/MappingCard.svelte [hunk 2]
```diff
@@ -23,8 +23,8 @@
 	}
 
 	function handleDelete() {
-		if (confirm('Are you sure you want to delete this mapping?')) {
-			onDelete?.(mapping.uuid);
+		if (confirm('Are you sure you want to delete this mapping?'+ mapping.uuid  + '')) {
```
Comment (cmwylie19) [inline src/lib/components/controls/MappingCard.svelte]:
```suggestion
		if (confirm('Are you sure you want to delete this mapping?' + mapping.uuid  + '')) {
```

Comment (cmwylie19) [reply src/lib/components/controls/MappingCard.svelte]: needs s space, also does this even make sense since there may be multiple with the same UUID

**Comment by cmwylie19** [comment]
We need to clean up the update function if it is not used

File: cli/server/infrastructure/fileStore.ts [hunk 3]
```diff
@@ -485,12 +492,16 @@ export class FileStore {
...
+		// Strip hash field before saving to disk
+		const cleanMapping = { ...mapping };
+		delete cleanMapping.hash;
+
 		// Update or add the mapping
-		const existingIndex = existingMappings.findIndex((m) => m.uuid === mapping.uuid);
+		const existingIndex = existingMappings.findIndex((m) => m.hash === mapping.hash);
 		if (existingIndex >= 0) {
-			existingMappings[existingIndex] = mapping;
+			existingMappings[existingIndex] = cleanMapping;
```
Comment (mjnagel) [inline cli/server/infrastructure/fileStore.ts]: I think this code is unreachable since `existingMappings` will load from the file and not have hashes stored. We can probably clean it up.

File: cli/server/infrastructure/fileStore.ts [hunk 4]
```diff
@@ -522,8 +533,12 @@ export class FileStore {
 				let mappings: Mapping[] = (yaml.load(content) as Mapping[]) || [];
 
 				const originalLength = mappings.length;
+				// we need to re-calculate the hash
 				mappings = mappings.filter((m) => {
-					return `${m.control_id}:${m.uuid}` !== compositeKey;
+					console.log('Delete Mapping: ' + JSON.stringify(m));
+					m.hash = createHash('sha256').update(JSON.stringify(m)).digest('hex');
+					console.log('Delete  Hash: ' + m.hash);
+					return `${m.control_id}:${m.hash}` !== compositeKey;
```
Comment (mjnagel) [inline cli/server/infrastructure/fileStore.ts]: This is probably fine, but I think we could alternatively save the hash as a separate var (rather than on the map) and be able to skip the "cleaning" later?

```suggestion
					const hash = createHash('sha256').update(JSON.stringify(m)).digest('hex');
					return `${m.control_id}:${hash}` !== compositeKey;
```

File: cli/server/websocketServer.ts [hunk 5]
```diff
@@ -164,23 +165,31 @@ class WebSocketManager {
...
-						const compositeKey = `${mapping.control_id}:${mapping.uuid}`;
 						state.mappingsCache.set(compositeKey, mapping);
 
 						// Update indexes
 						const family = mapping.control_id.split('-')[0];
 						if (!state.mappingsByFamily.has(family)) {
 							state.mappingsByFamily.set(family, new Set<string>());
 						}
-						state.mappingsByFamily.get(family)?.add(mapping.uuid);
+						state.mappingsByFamily.get(family)?.add(mapping.hash!);
```
Comment (mjnagel) [inline cli/server/websocketServer.ts:187]: This could be a cleanup later, but I think `mappingsByFamily` is unused at this point and a remnant of the time before we had advanced filtering.

File: cli/server/websocketServer.ts [hunk 6]
```diff
@@ -225,28 +254,40 @@ class WebSocketManager {
...
+						for (const [key, value] of state.mappingsCache.entries()) {
+							// the hash that is getting sent is the UUID
+
+							if (value.hash === hash) {
+								console.log(`Key ${key}\n Value hash: ${value.hash}\n Looking for hash: ${hash}`);
+								mapping = value;
+								compositeKeyToDelete = key;
+								break;
+							}
+						}
```
Comment (mjnagel) [inline cli/server/websocketServer.ts]: Could just do a direct `state.mappingsCache.get()` here if we passed the composite key in rather than just the hash?

File: src/lib/components/controls/tabs/MappingsTab.svelte [hunk 7]
```diff
@@ -80,29 +89,31 @@
...
+		if (!mappingToDelete) {
+			console.error('Mapping not found for deletion');
+			return;
+		}
+
 		try {
-			const compositeId = `${control.id}:${uuid}`;
-			await wsClient.deleteMapping(compositeId);
+			// Backend expects UUID for file operations
+			await wsClient.deleteMapping(mappingToDelete.hash!);
```
Comment (mjnagel) [inline src/lib/components/controls/tabs/MappingsTab.svelte]: This is where I think if we passed the (new) composite key, we could skip looping over the cache on the backend.

**Review by mjnagel — COMMENTED** [review]
Looks pretty good overall - I know there's still some cleanup of `console.log` statements so didn't comment on those but had a few other notes in reviewing.

File: src/lib/components/controls/MappingCard.svelte (hunk 2 above)
Comment (cmwylie19) [reply src/lib/components/controls/MappingCard.svelte]: Created an issue around this - https://github.com/defenseunicorns/lula/issues/350

File: cli/server/infrastructure/fileStore.ts (hunk 3 above)
Comment (cmwylie19) [reply cli/server/infrastructure/fileStore.ts]: Yep, good eye, existing mappings will not have hashes. Cleaning it up in the code

File: cli/server/infrastructure/fileStore.ts (hunk 4 above)
Comment (cmwylie19) [reply cli/server/infrastructure/fileStore.ts]: oh yes, that is much cleaner. Adding that in the code and deleting the hash cleanup from the mappings.

File: cli/server/websocketServer.ts (hunk 5 above)
Comment (cmwylie19) [reply cli/server/websocketServer.ts:187]: Yes I think you are right. I was trying to figure out the point and I was afraid to touch it bc i was wondering if it had something to do with spreadsheetRoutes. 

Here is an issue for that - https://github.com/defenseunicorns/lula/issues/351

File: src/lib/components/controls/tabs/MappingsTab.svelte (hunk 7 above)
Comment (cmwylie19) [reply src/lib/components/controls/tabs/MappingsTab.svelte]: Yes definitely

File: cli/server/websocketServer.ts (hunk 6 above)
Comment (cmwylie19) [reply cli/server/websocketServer.ts]: Yes - we definitely can. Good eye.

**Review by mjnagel — APPROVED** [review]
