### PR TITLE
fix: update cci definitions for separation

### LINKED ISSUE #333: UI Readability Issues
### Environment

Minor UI readability issues like CCI Definitions are one long paragraph “003605: Designate an organization-defined official to manage the development and documentation of the access control policy and procedures.; 003606: Designate an organization-defined official to manage the dissemination of the access control policy and procedures.; 003607: Defines the official designated to manage the development, documentation, and dissemination of the access control policy and procedures.

Note: The same issue likely exists in the export, so this is partially related to #332

### PR DESCRIPTION
**Pull request by cmwylie19**
## Description

This creates newlines in between CCI strings to make the data more readable in the UI. There is no guarantee on the structure of the CI but we do get the data from the CCI field to see what "string" we need to match on. This is only relevant when there are multiple CCIs and the CCI Definition field becomes hard to read.  

## Related Issue

Fixes #333 

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: src/lib/components/controls/ControlDetailsPanel.svelte [hunk 1]
```diff
@@ -47,6 +47,55 @@
...
+		// Create a view model based on editedControl without mutating it
+		const viewModel = { ...editedControl };
+		
+		const cciDefinition = viewModel.cci_definition || viewModel['cci-definition'];
+		if (viewModel.cci && cciDefinition) {
+			// Split the CCI list, handling semicolon separation
+			const cciList = viewModel.cci
+				.split(';')
+				.map((cci: string) => cci.trim())
+				.filter((cci: string) => cci.length > 0);
```
Comment (mjnagel) [inline src/lib/components/controls/ControlDetailsPanel.svelte]: I think the split is problematic when a CCI definition includes semicolons in the definition. Take for example this one:

>   000002: Disseminate the organization-level; mission/business process-level;
  and/or system-level access control policy that addresses purpose, scope,
  roles, responsibilities, management commitment, coordination among
  organizational entities, and compliance to organization-defined personnel or
  roles.; 002107: Defines the personnel or roles to be recipients of the
  organization-level; mission/business process-level; and/or system-level access
  control policy necessary to facilitate the implementation of the access
  control policy and associated access controls.

It ends up getting split on `;` and then anything in between a `;` and the next CCI gets cut off:
Image

Comment (cmwylie19) [reply src/lib/components/controls/ControlDetailsPanel.svelte]: good point - i am also noticing we have lost a CSS class or something, it is no longer bold

**Review by mjnagel — APPROVED** [review]
